name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check current working directory
        run: ls

      - name: Move to backend folder
        run: cd backend

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - run: cd backend && npm ci
      - run: cd backend && npm run build
      - run: cd backend && npm run lint

      - name: Use Next.js
      - run: cd frontend && npm ci
      - run: cd frontend && npm run build
      - run: cd frontend && npm run lint
